# Workflow config
scheduler: "pbs" # pbs,local - job scheduler
deployment: "colocated" # colocated,clustered - deployment approach for workflow components

# Dragon Distributed Dictionary config
dict:
    num_nodes: 1 # int - number of nodes across which to launch the dictionary
    managers_per_node: 1 # int - number of dictionary managers per node
    mem_size_per_node: 128 # int - managed memory size for each dictionary node in GB
    cpu_bind: [54,55,62,63] # list - CPU binding for the dictionary

# Simulation config
sim:
    executable: "" # string - path to simulation executable
    arguments: "" # string - command line arguments to simulation
    num_nodes: 1 # int - number of nodes across which to launch the simulation
    procs: 1 # integer - number of MPI processes for simulation
    procs_pn: 1 # integer - number of MPI processes per node for simulation
    cpu_bind: [0,8,16,24,32,40,48,56] # list - CPU binding for simulation

# Distributed training config
train:
    executable: "" # string - path to ML training executable
    config_path: "" # string - override path for training config file
    config_name: "" # string - override name of training config file
    num_nodes: 1 # int - number of nodes across which to launch ML training
    procs: 1 # integer - number of MPI processes for ML training
    procs_pn: 1 # integer - number of MPI processes per node for ML training
    cpu_bind: [4,12,20,28,36,44,52,60] # list - CPU binding for ML training

   
